config: 
  send_anonymous_usage_stats: False
  use_colors: True


snowflake-creds: &snowflake-creds
  type: snowflake
  account: "{{env_var('DBT_SNOWFLAKE_ACCOUNT')}}"
  user: "{{env_var('DBT_SNOWFLAKE_USER')}}"
  password: "{{env_var('DBT_SNOWFLAKE_PASSWORD')}}"
  database: DEMO
  role: "{{env_var('DBT_SNOWFLAKE_ROLE')}}"
  warehouse: "{{env_var('DBT_SNOWFLAKE_WH')}}"
  threads: 8
  client_session_keep_alive: False


cb_customizations:
  outputs:
    standard_dev:
      <<: *snowflake-creds
      schema: STANDARD_DEV
    standard_qa:
      <<: *snowflake-creds
      schema: STANDARD_QA
    standard_main:
      <<: *snowflake-creds
      schema: STANDARD_MAIN
    client1_dev:
      <<: *snowflake-creds
      schema: CLIENT1_DEV
    client1_qa:
      <<: *snowflake-creds
      schema: CLIENT1_QA
    client1_main:
      <<: *snowflake-creds
      schema: CLIENT1_MAIN
    client2_dev:
      <<: *snowflake-creds
      schema: CLIENT2_DEV
    client2_qa:
      <<: *snowflake-creds
      schema: CLIENT2_QA
    client2_main:
      <<: *snowflake-creds
      schema: CLIENT2_MAIN
  target: dev