version: 2

sources:
  - name: cb_general
    database: cb_general
    schema: public 
    tables:
      - name: invoices
        description: invoices used for test data
        columns:
          - name: dim_invoice
            description: primary key
            tests:
              - unique
              - not_null
          - name: amount
          - name: supplier_id
            tests:
              - not_null
      - name: suppliers
        description: suppliers used for test data
        columns:
          - name: supplier_id
            description: primary key
            tests:
              - unique
              - not_null
          - name: name
          - name: country
