USE ROLE ACCOUNTADMIN;

GRANT ROLE CB_ADMIN TO USER DBT_DEMO;
GRANT ROLE CB_DEV TO USER DBT_DEMO;
GRANT ROLE CB_STANDARD TO USER DBT_DEMO;
GRANT ROLE CB_CLIENT1 TO USER DBT_DEMO;
GRANT ROLE CB_CLIENT2 TO USER DBT_DEMO;

GRANT ROLE CB_ADMIN TO USER OGIERPAULPERSO;
GRANT ROLE CB_DEV TO USER OGIERPAULPERSO;
GRANT ROLE CB_STANDARD TO USER OGIERPAULPERSO;
GRANT ROLE CB_CLIENT1 TO USER OGIERPAULPERSO;
GRANT ROLE CB_CLIENT2 TO USER OGIERPAULPERSO;