USE ROLE CB_ADMIN;
USE WAREHOUSE CB_WH;

CREATE TABLE IF NOT EXISTS CB_GENERAL.PUBLIC.INVOICES (
DIM_INVOICE INTEGER PRIMARY KEY,
AMOUNT FLOAT,
SUPPLIER_ID INTEGER
);
TRUNCATE CB_GENERAL.PUBLIC.INVOICES;
INSERT INTO CB_GENERAL.PUBLIC.INVOICES VALUES (1, 11, 1);
INSERT INTO CB_GENERAL.PUBLIC.INVOICES VALUES (2, 8, 1);
INSERT INTO CB_GENERAL.PUBLIC.INVOICES VALUES (3, 22, 2);
INSERT INTO CB_GENERAL.PUBLIC.INVOICES VALUES (4, 10, 2);
INSERT INTO CB_GENERAL.PUBLIC.INVOICES VALUES (5, 15, 3);

CREATE TABLE IF NOT EXISTS CB_GENERAL.PUBLIC.SUPPLIERS (
SUPPLIER_ID INTEGER PRIMARY KEY,
NAME VARCHAR,
COUNTRY VARCHAR
);
TRUNCATE CB_GENERAL.PUBLIC.SUPPLIERS;
INSERT INTO CB_GENERAL.PUBLIC.SUPPLIERS VALUES (1, 'Supplier Foo GmbH', 'DE');
INSERT INTO CB_GENERAL.PUBLIC.SUPPLIERS VALUES (2, 'Bar Supplier SAS', 'FR');
INSERT INTO CB_GENERAL.PUBLIC.SUPPLIERS VALUES (3, 'SupBaz LTD', 'UK');