// Create a warehouse and create safety barriers to avoid costs overrun for the PoC
CREATE WAREHOUSE IF NOT EXISTS CB_WH ;
CREATE OR REPLACE RESOURCE MONITOR CB_LIMIT WITH CREDIT_QUOTA=50 TRIGGERS ON 70 PERCENT DO SUSPEND ON 90 PERCENT DO SUSPEND_IMMEDIATE;
ALTER WAREHOUSE CB_WH SET AUTO_SUSPEND = 60;
ALTER WAREHOUSE CB_WH SET STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 300;
ALTER WAREHOUSE CB_WH SET STATEMENT_TIMEOUT_IN_SECONDS = 60 ;
ALTER WAREHOUSE CB_WH SET RESOURCE_MONITOR = 'CB_LIMIT';

// Create the 5 roles: Admin, Dev, and Prod roles: Standard, Client1, Client2
CREATE ROLE IF NOT EXISTS CB_ADMIN;
CREATE ROLE IF NOT EXISTS CB_DEV;
CREATE ROLE IF NOT EXISTS CB_STANDARD ;
CREATE ROLE IF NOT EXISTS CB_CLIENT1;
CREATE ROLE IF NOT EXISTS CB_CLIENT2;


GRANT USAGE ON WAREHOUSE CB_WH TO ROLE CB_ADMIN;
GRANT USAGE ON WAREHOUSE CB_WH TO ROLE CB_DEV;
GRANT USAGE ON WAREHOUSE CB_WH TO ROLE CB_STANDARD;
GRANT USAGE ON WAREHOUSE CB_WH TO ROLE CB_CLIENT1;
GRANT USAGE ON WAREHOUSE CB_WH TO ROLE CB_CLIENT2;

// Create 6 databases: standard, dev, client1, client2, and general and admin
// Admin will have admin rights on each
// Then each of the four target roles (Standard, dev, client1, client2) will have access only to their own and general
CREATE DATABASE IF NOT EXISTS  CB_STANDARD;
CREATE DATABASE IF NOT EXISTS  CB_DEV;
CREATE DATABASE IF NOT EXISTS  CB_CLIENT1;
CREATE DATABASE IF NOT EXISTS CB_CLIENT2;
CREATE DATABASE IF NOT EXISTS  CB_GENERAL;
CREATE DATABASE IF NOT EXISTS CB_ADMIN;

CREATE SCHEMA IF NOT EXISTS CB_STANDARD.PROD;
CREATE SCHEMA IF NOT EXISTS CB_CLIENT1.PROD;
CREATE SCHEMA IF NOT EXISTS CB_CLIENT2.PROD;
CREATE SCHEMA IF NOT EXISTS CB_DEV.DEV;
CREATE SCHEMA IF NOT EXISTS CB_DEV.STG;

CREATE SCHEMA IF NOT EXISTS CB_ADMIN.ADMIN;
CREATE SCHEMA IF NOT EXISTS CB_GENERAL.PUBLIC;

GRANT ALL PRIVILEGES ON DATABASE CB_STANDARD TO ROLE CB_ADMIN WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON DATABASE CB_DEV TO ROLE CB_ADMIN WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON DATABASE CB_CLIENT1 TO ROLE CB_ADMIN WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON DATABASE CB_CLIENT2 TO ROLE CB_ADMIN WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON DATABASE CB_ADMIN TO ROLE CB_ADMIN WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON DATABASE CB_GENERAL TO ROLE CB_ADMIN WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE CB_STANDARD TO ROLE CB_ADMIN WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE CB_DEV TO ROLE CB_ADMIN WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE CB_CLIENT1 TO ROLE CB_ADMIN WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE CB_CLIENT2 TO ROLE CB_ADMIN WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE CB_ADMIN TO ROLE CB_ADMIN WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE CB_GENERAL TO ROLE CB_ADMIN WITH GRANT OPTION;

GRANT SELECT ON FUTURE TABLES IN SCHEMA CB_STANDARD.PROD TO ROLE CB_ADMIN WITH GRANT OPTION;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CB_DEV.DEV TO ROLE CB_ADMIN WITH GRANT OPTION;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CB_DEV.STG TO ROLE CB_ADMIN WITH GRANT OPTION;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CB_CLIENT1.PROD TO ROLE CB_ADMIN WITH GRANT OPTION;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CB_CLIENT2.PROD TO ROLE CB_ADMIN WITH GRANT OPTION;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA CB_STANDARD.PROD TO ROLE CB_ADMIN WITH GRANT OPTION;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA CB_DEV.DEV TO ROLE CB_ADMIN WITH GRANT OPTION;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA CB_DEV.STG TO ROLE CB_ADMIN WITH GRANT OPTION;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA CB_CLIENT1.PROD TO ROLE CB_ADMIN WITH GRANT OPTION;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA CB_CLIENT2.PROD TO ROLE CB_ADMIN WITH GRANT OPTION;


GRANT USAGE ON DATABASE CB_STANDARD TO ROLE CB_STANDARD;
GRANT USAGE ON DATABASE CB_DEV TO ROLE CB_DEV;
GRANT USAGE ON DATABASE CB_CLIENT1 TO ROLE CB_CLIENT1;
GRANT USAGE ON DATABASE CB_CLIENT2 TO ROLE CB_CLIENT2;


GRANT USAGE ON SCHEMA CB_STANDARD.PROD TO ROLE CB_STANDARD;
GRANT USAGE ON SCHEMA CB_CLIENT1.PROD TO ROLE CB_CLIENT1;
GRANT USAGE ON SCHEMA CB_CLIENT2.PROD TO ROLE CB_CLIENT2;
GRANT USAGE ON SCHEMA CB_DEV.DEV TO ROLE CB_DEV;
GRANT USAGE ON SCHEMA CB_DEV.STG TO ROLE CB_DEV;

GRANT ALL PRIVILEGES ON SCHEMA CB_STANDARD.PROD TO ROLE CB_STANDARD;
GRANT ALL PRIVILEGES ON SCHEMA CB_CLIENT1.PROD TO ROLE CB_CLIENT1;
GRANT ALL PRIVILEGES ON SCHEMA CB_CLIENT2.PROD TO ROLE CB_CLIENT2;
GRANT ALL PRIVILEGES ON SCHEMA CB_DEV.DEV TO ROLE CB_DEV;
GRANT ALL PRIVILEGES ON SCHEMA CB_DEV.STG TO ROLE CB_DEV;

GRANT USAGE ON SCHEMA CB_GENERAL.PUBLIC TO ROLE CB_STANDARD;
GRANT USAGE ON SCHEMA CB_GENERAL.PUBLIC TO ROLE CB_CLIENT1;
GRANT USAGE ON SCHEMA CB_GENERAL.PUBLIC TO ROLE CB_CLIENT2;
GRANT USAGE ON SCHEMA CB_GENERAL.PUBLIC TO ROLE CB_DEV;

GRANT SELECT ON FUTURE TABLES IN SCHEMA CB_GENERAL.PUBLIC TO ROLE CB_STANDARD;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CB_GENERAL.PUBLIC TO ROLE CB_CLIENT1;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CB_GENERAL.PUBLIC TO ROLE CB_CLIENT2;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CB_GENERAL.PUBLIC TO ROLE CB_DEV;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA CB_GENERAL.PUBLIC TO ROLE CB_STANDARD;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA CB_GENERAL.PUBLIC TO ROLE CB_CLIENT1;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA CB_GENERAL.PUBLIC TO ROLE CB_CLIENT2;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA CB_GENERAL.PUBLIC TO ROLE CB_DEV;









