name: Update Main Branches

on:
  pull_request:
    branches:
      - main


jobs:
  build-and-test-the-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch the complete history

    - name: Fetch the latest changes from main
      run: git fetch origin main

    - name: Merge the latest changes from main
      run: git merge --ff-only origin/main

    - name: Run tests
      run: echo "$(<Readme.md)"
