name: Update Main Branches

on:
  pull_request:
    branches:
      - main


jobs:
  build-and-test-the-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch the complete history

    - name: Fetch the latest changes from main
      run: git fetch origin main

    - name: Merge the latest changes from main
      run: git merge --ff-only origin/main

    - name: Run tests
      run: | 
        echo "$(<Readme.md)"
        PR_BRANCH=${GITHUB_HEAD_REF/refs\/heads\//}
        echo $PR_BRANCH
    
  test_on_prod_branches:
    runs-on: ubuntu-latest
    needs: build-and-test-the-pull-request
    strategy:
        matrix:
          branch: ['main1', 'main2']
    
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            fetch-depth: 0  # Fetch the complete history
        
        # - name: Fetch the latest changes from the client branch
        #   run: git fetch origin ${{ matrix.branch }}
        
        # - name: Merge changes into main branch
        #   run: |
        #     git merge --no-ff ${{ github.event.before }} ${{ github.sha }}
        #     if [ $? -ne 0 ]; then
        #         echo "Merge into ${{ matrix.branch }} failed. Resolve conflicts and try again."
        #         exit 1
        #     fi
        - name: Run tests
          run: |
            echo "$(<Readme.md)" 
            echo "${{ matrix.branch }}"
            echo $PR_BRANCH
