name: Update Main Branches

on:
  pull_request:
    branches:
      - main


jobs:
  build-and-test-the-pull-request:
    runs-on: ubuntu-latest
    outputs:
        pr_branch: ${{ steps.identify-github-pr-branch-name.outputs.pr_branch }}

    steps:
    - id: identify-github-pr-branch-name
      run: |
        PR_BRANCH=${GITHUB_HEAD_REF/refs\/heads\//}
        echo $PR_BRANCH
        echo "PR_BRANCH=$PR_BRANCH" >> "$GITHUB_OUTPUT"
    # - name: Checkout code
    #   uses: actions/checkout@v2
    #   with:
    #     fetch-depth: 0  # Fetch the complete history

    # - name: Fetch the latest changes from main
    #   run: git fetch origin main

    # - name: Merge the latest changes from main
    #   run: git merge --ff-only origin/main

    - name: Run tests
      env:
        PR_BRANCh: ${{ steps.identify-github-pr-branch-name.outputs.PR_BRANCH }}
      run: | 
        echo "$(<Readme.md)"
        echo $PR_BRANCH
    
  test_on_prod_branches:
    runs-on: ubuntu-latest
    needs: build-and-test-the-pull-request
    strategy:
        matrix:
          branch: ['main1', 'main2']
    
    steps:
        - name: echo matrix branch
          run: echo ${{ matrix.branch }}
        # - name: Checkout code
        #   uses: actions/checkout@v4
        #   with:
        #     fetch-depth: 0  # Fetch the complete history  
        #     ref: ${{ matrix.branch }}
  
        # - name: Run tests
        #   run: echo "$(<Readme.md)" 
        - name: echo pr branch
          env:
            PR_BRANCh: ${{ steps.identify-github-pr-branch-name.outputs.PR_BRANCH }}
          run: |
             echo "$PR_BRANCH"
        # - name: Checkout code
        #   uses: actions/checkout@v4
        #   with:
        #     fetch-depth: 0  # Fetch the complete history
        #     ref: ${{ build-and-test-the-pull-request.identify-github-pr-branch-name.outputs.pr_branch}}   
        # - name: Run tests
        #   run: echo "$(<Readme.md)" 