# Deployment pipeline 
name: Development

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:
    
env:
  DBT_PROFILES_DIR: ./
  DBT_SNOWFLAKE_USER: ${{ secrets.DBT_SNOWFLAKE_USER}}
  DBT_SNOWFLAKE_PASSWORD: ${{ secrets.DBT_SNOWFLAKE_PASSWORD}}
  DBT_SNOWFLAKE_ROLE: ${{ secrets.DBT_SNOWFLAKE_ROLE }}
  DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}
  DBT_SNOWFLAKE_WH: ${{ secrets.DBT_SNOWFLAKE_WH }}

jobs:
  ci_test:
    name: test dbt
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      
      - uses: actions/setup-python@v1
        with:
          python-version: "3.9.18"

      - name: Test profiles existence
        run:  test -e profiles.yml
        working-directory: ./dbt

      - name: Install dependencies
        run:  pip install -r requirements.txt
      
      - name: install dbt packages
        run: dbt deps
        working-directory: ./dbt
      
      - name: Seed the model
        run: dbt seed
        working-directory: ./dbt

      - name: build and test (Full)
        run:  dbt build
        working-directory: ./dbt