name: Launch tests on different branches on a PR to main

on:
  push:
    branches:
      - main

env:
    DBT_PROFILES_DIR: ./
    DBT_SNOWFLAKE_USER: ${{ secrets.DBT_SNOWFLAKE_USER}}
    DBT_SNOWFLAKE_PASSWORD: ${{ secrets.DBT_SNOWFLAKE_PASSWORD}}
    DBT_SNOWFLAKE_ROLE: ${{ secrets.DBT_SNOWFLAKE_ROLE }}
    DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}
    DBT_SNOWFLAKE_WH: ${{ secrets.DBT_SNOWFLAKE_WH }}

jobs:
  build-on-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch the complete history
    - name: Install dependencies
      run:  pip install -r requirements.txt
    - name: Copy the previous manifest file from S3
      run: |
        aws s3 cp ${{secrets.AWS_S3_BUCKET}}/dbt-target/main/manifest.json /home/runner/work/cb_customizations/cb_customizations/dbt/manifest.json
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-central-1'   
    - name: install dbt packages
      run: dbt deps
      working-directory: ./dbt
    - name: build with slim CI
      run:  dbt build --target standard_main --select state:modified+ --state ./
      working-directory: ./dbt
    - name: Build docs
      run: dbt docs generate --target standard_main
      working-directory: ./dbt
    - name: Upload docs to S3
      run: aws s3 cp /home/runner/work/cb_customizations/cb_customizations/dbt/target/ ${{secrets.AWS_S3_BUCKET}}/dbt-target/main/ --recursive
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-central-1'

  merge-and-build-on-prod-branches:
    runs-on: ubuntu-latest
    needs: build-on-main
    strategy:
        matrix:
          branch: [['main1', 'client1_main'], ['main2', 'client2_main']]
    
    steps:
        - name: echo matrix branch and associated schema
          run: |
            echo ${{ matrix.branch[0]}}
            echo ${{ matrix.branch[1]}} 
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0  # Fetch the complete history  
            ref: ${{ matrix.branch[0]}}
            token: ${{ secrets.GH_TOKEN }}
        - name: authenticate
          run: |
            git config user.name ogierpaul
            git config user.email ogier.paul@gmail.com
        - name: Merge pull request branch into main1
          run: git merge --no-ff origin/main
        - name: Install dependencies
          run:  pip install -r requirements.txt
        - name: Copy the previous manifest file from S3
          run: |
            aws s3 cp ${{secrets.AWS_S3_BUCKET}}/dbt-target/${{ matrix.branch[0]}}/manifest.json /home/runner/work/cb_customizations/cb_customizations/dbt/manifest.json
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: 'eu-central-1'   
        - name: install dbt packages
          run: dbt deps
          working-directory: ./dbt
        - name: build with slim CI
          run:  dbt build --target ${{ matrix.branch[1]}} --select state:modified+ --state ./
          working-directory: ./dbt
        - name: Build docs
          run: dbt docs generate --target ${{ matrix.branch[1]}}
          working-directory: ./dbt
        - name: Upload the new manifest to S3
          run: aws s3 cp /home/runner/work/cb_customizations/cb_customizations/dbt/target/ ${{secrets.AWS_S3_BUCKET}}/dbt-target/${{ matrix.branch[0]}}/ --recursive
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: 'eu-central-1'
        - name: commit and push
          run: git push origin ${{ matrix.branch[0]}}
